In [65]:
import numpy as np 
import pandas as pd

In [66]:
df = pd.read_csv('IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [67]:
df = df.iloc[:10000]
df.shape

(10000, 2)

In [68]:
df["review"][1]
# df["sentiment"][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [69]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [70]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [71]:
df.duplicated().sum()

np.int64(17)

In [72]:
df = df.drop_duplicates()
df.shape

(9983, 2)

In [73]:
import re 

def remove_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [74]:
df['review'] = df['review'].apply(remove_tags)
df['review'][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [75]:
df['review']= df['review'].apply(lambda x: x.lower())
df['review'][1]

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [76]:
# import nltk
# nltk.download('stopwords')

In [77]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x: ' '.join(x))

In [78]:
df

                                                 review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [79]:
import gensim
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Chandani\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Chandani\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [80]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

In [81]:
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc,language='english')
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [82]:
model = gensim.models.Word2Vec(vector_size=100, window=10, min_count=2)

In [83]:
model.build_vocab(story)

In [84]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5849786, 6186875)

In [85]:
len(model.wv.index_to_key)

31845

In [86]:
def document_vector(doc):
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [87]:
document_vector(df['review'][1])

array([-3.48596245e-01,  6.42081380e-01, -1.05644286e-01, -1.87160268e-01,
        7.44514633e-03, -5.74438572e-01,  8.02523792e-02,  5.37069440e-01,
       -2.79341191e-01,  4.64350618e-02, -2.43692026e-01, -7.78264999e-01,
       -1.56295359e-01, -3.59672345e-02,  2.42683887e-01, -2.97471613e-01,
        3.19298089e-01, -3.85336846e-01,  6.07709214e-03, -8.67848933e-01,
        1.74159423e-01,  3.89710754e-01,  2.93964714e-01, -1.05038278e-01,
       -5.00745066e-02,  2.96819359e-01, -5.05160391e-01, -5.23560643e-01,
       -3.37973982e-01, -2.52674490e-01,  4.54478413e-01,  2.65466690e-01,
        1.90986738e-01, -3.84218335e-01,  7.52778128e-02,  4.53920811e-01,
       -1.83077753e-01, -5.11329889e-01, -4.63885099e-01, -5.12848556e-01,
       -1.61547996e-02, -5.73944867e-01, -3.74437064e-01, -2.13734694e-02,
        4.14627314e-01, -2.90178925e-01, -3.53245199e-01,  3.33345346e-02,
        1.43449947e-01,  3.43865901e-01,  1.35286987e-01, -2.35998020e-01,
       -2.15940833e-01, -5.07229865e-02, -1.25238135e-01,  2.68248409e-01,
        8.24846476e-02, -1.87238753e-01, -5.38975537e-01, -6.15019933e-04,
        5.03081568e-02,  1.67854384e-01, -3.12247872e-02,  8.54786187e-02,
       -3.24156612e-01,  2.95485586e-01,  1.00212671e-01,  2.54968494e-01,
       -3.10254902e-01,  4.42745447e-01, -1.48423970e-01,  3.78660858e-01,
        4.39824373e-01, -2.08405983e-02,  5.54885328e-01,  3.48742642e-02,
        1.28352761e-01, -1.03011653e-02, -3.12425047e-02,  9.50554088e-02,
       -3.67660105e-01, -2.77842104e-01, -4.23527002e-01,  5.58436930e-01,
       -4.98477928e-02, -6.29268959e-02, -3.80705744e-02,  3.72583419e-01,
        3.07102919e-01,  1.91539094e-01,  7.99716234e-01,  3.99658442e-01,
        1.63191214e-01,  1.26184881e-01,  6.66393101e-01,  4.67240095e-01,
        3.03210109e-01, -4.42488372e-01, -8.53512809e-02,  3.79954353e-02],
      dtype=float32)

In [88]:
from tqdm import tqdm

In [89]:
X = []
for doc in tqdm(df['review']):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [05:49<00:00, 28.55it/s]

In [90]:
X = np.array(X)
X.shape

(9983, 100)

In [92]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df['sentiment'])
y.shape

(9983,)

In [93]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [95]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [98]:
from sklearn.metrics import confusion_matrix, accuracy_score
y = rfc.predict(X_test)
accuracy_score(y_test, y)

0.7796695042563846